server:
  port : 9082
tigerProxy:
  port: 9443
  serverIdentity: "tls.crt;tls.key;PKCS8"
  proxyLogLevel: TRACE
  fileSaveInfo:
    writeToFile: true
  proxyRoutes:
    - from: /
      to: https://context-manager-service:9443
