tigerProxy:
  # Der Port auf dem der Traffic angeschaut werden kann
  adminPort: 8080
  # Der Port welcher den Traffic weiterleitet
  proxyPort: 4742
  directReverseProxy:
##################################################################
#  Hier das Kartenterminal eintragen welches gespiegelt werden soll
##################################################################
    hostname: 10.150.9.173
    port: 4742
##################################################################
  tls:
    # Das Zertifikat welches dem Konnektor gezeigt wird (muss entsprechend das Zertifikat des KTs sein)
    serverIdentity: gsmckt.p12;00
    # Das Zertifikat welches dem KT gezeigt wird (muss entsprechend das Zertifikat des Konnektors sein)
    forwardMutualTlsIdentity: konnektor.p12;00
    # SSL-Suiten die beim Handshake gegen den Konnektor (als KT) verwendet werden
    serverSslSuites:
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_DHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_DHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_EMPTY_RENEGOTIATION_INFO_SCSV
    # SSL-Suiten die beim Handshake gegen das KT (als Konnektor) verwendet werden
    clientSslSuites:
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_DHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_DHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_EMPTY_RENEGOTIATION_INFO_SCSV
  # Konfiguration um den Verkehr des letzten Starts zu loggen
  fileSaveInfo:
    writeToFile: true
    # Soll beim Starten des Tiger-Proxy das Log gelöscht werden?
    clearFileOnBoot: true
    # Dateiname, in den geloggt wird
    filename: cats_traffic.tgr
