
@startuml

hide stereotype

' left to right direction

skinparam component {
    BackgroundColor Gold
    BorderColor DarkOrange
    BackgroundColor<<External>> LightGray
    BorderColor<<External>> Blue
    BackgroundColor<<Idp>> LightGreen
    BorderColor<<Idp>> Green
    BackgroundColor<<Other>> DeepSkyBlue
    BorderColor<<Other>> Blue
    BackgroundColor<<NextRelease>> LightGray
    FontColor<<NextRelease>> Gray
    BorderColor<<NextRelease>> Gray
    ArrowColor<<HTTP>> DodgerBlue
    FontColor<<HTTP>> Gray
    ArrowFontColor DarkOrange
    ArrowThickness 1
}

skinparam interface {
    BorderColor<<HTTP>> DodgerBlue
}


' left to right direction

' component TigerServer  <<NextRelease>>

package TestSystems as tsys {
    component "RU/TU service instances" as rutu <<External>>
    component "locally started\ndocker containers" as locdock <<Other>>

    component "cloud based\ndocker containers" as clddock <<NextRelease>>
    component "Simulators" as sims <<NextRelease>>
}

component TigerEnvMgr as tem
component TigerProxy as tp

package TestSuitePool as suites {
    component "Idp test suite" as its <<Idp>>
    component "Other test suites" as ots <<Other>>
    component TigerTestLib [
      TigerTestLib
      ---
      Basic steps
      ---
      PolarionConnector
      Context
      Variables
      JSONChecker
      AfoReporter
      TestCodeParser
      TestResultParser
      SerenityIntegration
    ]
}

component "Current Testsuite" as tdir <<Other>>



' tem
interface ITestEnvironment as item
' tp
interface "Local Http traffic" as ihttp <<HTTP>>
interface "ProxyConfiguration" as ipconf
' ts
interface "IRBelMessaging" as irbel
'tsys
interface "Routed HTTP traffic" as iroutes <<HTTP>>
'suites
' interface "Steps" as isteps
' interface "Helpers" as ihelpers
interface "Reuse" as ireuse


ihttp -down- tp <<HTTP>>
tdir --> ihttp <<HTTP>> : test traffic

irbel -up-> tdir
tp -up-> irbel : return traffic\nmessages\nform test traffic


iroutes -left- tsys <<HTTP>>
tp --> iroutes <<HTTP>> : routed test traffic

ipconf -- tp
tem --> ipconf : configure URLs, \nURL mappings and certs

item -left- tem
tdir -left-> item : build me\na test env


ireuse -left- suites
tdir -right-> ireuse

@enduml