@startuml

!include plantuml.style

hide stereotype


' left to right direction

' component TigerServer  <<NextRelease>>

component tsys <<Other>> [
     Testsysteme

     ---

     RU/TU service instances
     locally started docker containers
     helm charts
     Simulators
]


component Serenity <<Other>> [
    <img:https://pbs.twimg.com/profile_images/875117009171820544/Kgy599vq_400x400.jpg{scale=0.207}>
    <color:white><b>Serenity BDD</b></color>
]

rectangle Tiger as tiger {
component TigerTestEnvMgr as tem <<Tiger>>
component TigerProxy as tp <<Tiger>>

component TigerTestLib <<Tiger>>

component tex <<Tiger>> [
    Tiger Extensions

    ---

    Cloud
    Konnektormanagement
    CATS
    PSSim
    HTTP Client
    FHIR validation
    Zi0n mock server
    Kartenterminal Robot
]

'suites
' interface "Steps" as isteps
' interface "Helpers" as ihelpers
' interface "Reuse" as ireuse
' tem
' interface ITestEnvironment as item
' tp
' interface "Local Http traffic" as ihttp <<HTTP>>
' interface "ProxyConfiguration" as ipconf
' ts
' interface "IRBelMessaging" as irbel

component "Current Testsuite" as tdir <<Current>>



}

component Polarion <<Other>> [
    <img:https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/0024/4635/brand.gif?itok=imrp3xNh{scale=0.5}>
]

component TestSuitePool as suites <<Other>>

'tsys

tdir --> tp <<HTTP>> : traffic of\ntest run

tp -up-> tdir : return\ntraffic data

tp -left-> tsys <<HTTP>> : routed test traffic

tem --> tp : configure\nroutes and PKI

tdir -left-> tem : build me\na test env
tdir -left-> tex : use

tem -left-> tsys
tdir <-up- suites : reuse
tdir -down- TigerTestLib : reuse

TigerTestLib -down--> Serenity : detailed\ntest reports

Serenity -right-> Polarion
TigerTestLib -left-> Polarion : sync\ntest spec\nand reports
@enduml
