[#_tiger_test_environment_manager]
== Tiger Test Environment Manager

As outlined in xref:tiger_user_manual.adoc#_overview[the overview section], the test environment manager is one of the three core components of the Tiger test framework.
Its main task is to start various test server nodes configured in the `tiger.yaml` configuration file and initialize the local tiger proxy for the test suite.

=== Tiger.yaml files and how they are chosen and loaded

The test environment manager first checks if the environment variable `TIGER_TESTENV_CFGFILE` is set and tries to load the configuration file from this value.
If the environment variable is not set, it searches for files named `tiger.yaml` or `tiger.yml`.
If none of these files exist, it will fail the start-up.

It then loads further YAML files:

* `tiger-$+{hostname}+.yaml` and `tiger-$+{hostname}+.yml` are read and allow computer-dependent configuration.
The hostname is the name of your own computer in the network (on Windows machines, typically the computer name).
* `tiger-$+{profile}+.yaml` is read if the system property `profile` or the environment variable `PROFILE` is set.
The file must be located in the same folder as the `tiger.yaml` file.
Additionally, you can configure a default profile in the Tiger configuration, which will be loaded when none is set via environment variable or system property.
See xref:tigerTestLibrary.adoc#_tiger_test_lib_configuration[Tiger test lib configuration] for more details.

During the start-up phase it also informs the local tiger proxy about the hostnames each node has configured, so that the local tiger proxy can create appropriate routing entries in its own configuration.

To configure your test environment, you can compose the `tiger.yaml` file manually.
There is a JSON schema available for your IDE to assist with editing the `tiger.yaml`: https://json.schemastore.org/gematik-tiger.json.

The nodes configured in the YAML file are started asynchronously unless the `dependsUpon` property is set.

One optional but powerful server type is `canopy`, a DNS server that can intercept and dynamically reroute selected hostnames to the Tiger proxy at runtime.
This enables test scenarios to change routing configuration without restarting the environment, making it ideal for multi-scenario testing, chaos injection, and hypothesis testing.
For details on why and how to use Canopy, see xref:../../tiger-canopy/doc/CANOPY-USER-GUIDE.md[the Canopy User Guide].

Before writing your own `tiger.yaml` configuration files, ensure you are familiar with YAML syntax and structure.

[#_yaml_loading_and_overriding]
=== YAML loading and overriding logic

The Tiger test environment loads configuration from several YAML files, depending on environment variables, hostnames, and profiles.
The order and logic are as follows:

- If the environment variable `TIGER_TESTENV_CFGFILE` is set, this file is loaded first.
- If not, `tiger.yaml` or `tiger.yml` in the working directory is loaded.
- Hostname-specific files (`tiger-${hostname}.yaml` or `.yml`) are loaded next.
- Profile-specific files (`tiger-${profile}.yaml`) are loaded if a profile is set via system property or environment variable.
- Additional configuration files can be loaded via the `tiger.additionalConfigurationFiles` list in the main config.

For details, see xref:tigerConfiguration.adoc#_additional_yaml_files[Additional YAML files].

==== Exports

All `exports` entries of a node are available for subsequent nodes and can be used in their configuration (e.g. in Docker `environment`, tiger proxy `proxyRoutes`, etc.).


<<<

include::serverTypes.adoc[]

=== Server type example

Here is a little example of how the server names are set and used and how the server is reachable via the tiger proxy.

[source,yaml,title="Example with three external jar servers"]
----
servers:
# here the server name is "identityServer" and
# the server is reachable under "identityServer" via the tiger proxy
  identityServer:
    type: externalJar
    # important: the source entry must not contain any spaces.
    source:
      - local:../octopus-identity-service/target/octopus-identity-service-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.identity}/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port=${tiger.ports.identity}
        - --services.shopping=http://myShoppingServer

  # here the server name is "shoppingServer"
  # but the server is reachable under "myShoppingServer" via the tiger proxy because hostname is set
  shoppingServer:
    hostname: myShoppingServer
    type: externalJar
    source:
      - local:../octopus-shopping-service/target/octopus-shopping-service-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.shopping}/inventory/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port = ${tiger.ports.shopping}
        - --services.identity=http://identityServer

  testClient:
    type: externalJar
    source:
      - local:../octopus-example-client/target/octopus-example-client-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.client}/testdriver/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port=${tiger.ports.client}
        # here are the examples how the servers are reachable
        - --services.shopping=http://myShoppingServer
        - --services.identity=http://identityServer
----

The general properties are followed by the type specific substructures, which configure specific aspects of each node type.
Their meaning and format are explained in the related section.

[source,yaml,title="Type specific properties"]
----
  # type specific sub structure for external jar, Tiger Proxy, docker and helm chart nodes
  externalJarOptions:
    # used by external jar and Tiger Proxy nodes
    workingDir: string
    # only used by external jar nodes
    options: []
    # used by external jar and Tiger Proxy nodes
    arguments: []
    # flag whether to forward log output from external jar processes to the workflow UI
    activateWorkflowLogs : true
    # flag whether to forward log output from external jar processes to workflow UI and console
    activateLogs: true

  # type specific sub structure for Tiger Proxy nodes
  tigerProxyConfiguration:
    # Here a normal Tiger Proxy configuration can be used.
    # This is explained in more depth down below
    adminPort: int
    proxiedServer: string
    proxiedServerProtocol: [HTTP|HTTPS]
    proxyRoutes:
        # defines a forward-proxy-route from this server
      - from: http://foobar
        # to this server
        to: https://cryptic.backend/server/with/path

  # type specific sub structure for docker container and compose nodes
  dockerOptions:
    # all properties below only used by docker container nodes
    proxied: boolean
    oneShot: boolean
    entryPoint: string
  # type specific sub structure for helm charts
  helmChartOptions:
    # context to install the helm chart to
    context:
    # name for the helm chart
    podName:
    # working directory for local helm and kubectl calls
    workingDir:
    # name space to install the helm chart to
    nameSpace:
    # flag whether to show more detailed infos about
    # the helm chart installation in the console
    debug:
    # list of regex names for pods to be running to signal
    # successful startup of helm chart **/
    healthcheckPods:
    # list of key value pairs to be used by the helm chart
    values:
    # comma separated list of port forwardings
    # Entries can be either "podNameRegex:xxxx", which is shorthand for
    # "podNameRegex:xxxx:xxxx or
    # "podNameRegex:xxxx:yyyy" where xxxx is the local port
    # and yyyy is the port in the pod
    exposedPorts:
    # list of regex for pod names logs should be shown
    logPods:

----

The configuration of the Tiger Proxy is explained in detail in the section xref:_configuring_the_local_test_suite_tiger_proxy[]

[#_configuring_pki_identities_in_tiger_proxys_tls_section]
==== Configuring PKI identities in Tiger Proxy's tls section

PKI identities can be supplied in a number of ways (JKS, BKS, PKCS1, PKCS8).
In every place a string can be given.
It could be one of

* "my/file/name.p12;p12password"
* "p12password;my/file/name.p12"
* "cert.pem;key.pkcs8"
* "rsaCert.pem;rsaKey.pkcs1"
* "key/store.jks;key"
* "key/store.jks;key1;key2"
* "key/store.jks;jks;key"

Not supported pathname strings:

* "D:\\myproject\\key\\store.jks;key"

Supported pathname string on all platforms:

* "myproject/key/store.jks;key"

Please notice, that double backslashes ("\\") are not supported as file separators, since they are not accepted on all platforms.
Invalid pathname strings will also produce an exception.

Each part can be one of:

* filename
* password
* store-type (accepted are P12, PKCS12, JKS, BKS, PKCS1 and PKCS8)

If you want, you can also describe the components in a map:

[source,yaml]
----
tls.forwardMutualTlsIdentity:
  filename: myIdentity.p12
  password: "changeit"
  storeType: P12
----

In this case both the storeType and the password are not mandatory and would be guessed (the store-type via the file extension and the password via a default-list).

===== PKI identity passwords

Tiger will attempt to decrypt a given P12 file with a list of common passwords, among these are:

----
"00", "123456", "gematik", "changeit"
----

Users can insert additional passwords by configuring the `tiger.yaml` as follows

----
lib:
    additionalKeyStorePasswords: ["foo", "bar", "baz"]
----

==== Docker Container node

The docker container node allows to instantiate a local docker container from the configured image.
The exposed port of the docker container is available as a special token in the substitution process of the exports entries (`${PORT:xxxx}` where xxxx is the port being exposed inside the container).

To customize the docker container you may alter the entry point command line.
Additionally, Tiger will automatically add the Tiger Proxy certificate to the container's operating system list of trusted certificates.
This modification can be disabled by setting the property `dockerOptions.proxied` to false.
E.g.:

[source,yaml]
----
servers:
  exampleDockerServer:
    type: docker
    dockerOptions:
        proxied: false # default is true
----

For containers that should exit after a single command you may enable the oneShot property.

You can also copy files to the container by configuring the source and destinations paths of files or folder to be copied.

If there is no health check configured inside the docker image, Tiger will try to guess a healthcheck url by assuming the first exposed port as a get request to localhost to check for a successful startup of the docker container (e.g. http://127.0.0.1:xxxx).

If no port is exposed at all, the startupTimeoutSec property will determine the wait period, after which Tiger assumes the container is up and running.

If you have your local docker environment set up hosting the docker containers on a remote docker hub server, you may set the environment variable `TIGER_DOCKER_HOST` to allow the health check url determined on runtime to point to the remote host instead of localhost.

NOTE: To use this server type you must include the tiger-cloud-extension dependency!

[source,yaml,title="Docker container configuration"]
----
servers:
    dockerContainer_001:
      hostname: myDockerContainer
      type: docker
      dependsUpon: csv string
      startupTimeoutSec: int

      # MANDATORY URL from where to download the docker image.
      source:
        - dockerhubrepo.somewhere.org/repo/project/docker.image
      # MANDATORY version of the docker image to download.
      version: 0.1.2
      # OPTIONAL the logs of the docker container are also written to a file, if no logFile is
      # specified a default name will be used
      logFile: ./target/serverLogs/dockerContainer_001.log

      dockerOptions:
        # OPTIONAL Flag whether the container shall be modified by
        # o adding the Tiger Proxy certificate to the container operating system.
        # o adding docker.host.internal to the container's /etc/hosts file.
        # Default value is true.
        proxied: true
        # OPTIONAL Flag whether the container is a one shot container or not.
        # One shot meaning it will execute a command and then stop.
        # Default value is false.
        oneShot: false
        # OPTIONAL The entry point command line to be used to start up this container
        # overwriting any configured entry point in the docker image.
        # Default value is empty meaning to use the configured entry point command line.
        entryPoint: chmod a+x /startup.sh && /startup.sh
        # OPTIONAL list of files to be copied to the container
        copyFiles:
          # path to the file or the folder to copy inside the container
          - sourcePath: ./example/path/file_to_copy.txt
          # path inside the container where the file should be copied to
            destinationPath: /path/in/container/file_to_copy.txt
          # OPTIONAL the file mode of the copied file as octal representation (see https://en.wikipedia.org/wiki/File-system_permissions#numericNotation
            fileMode: 0633
          # a complete folder can also be copied instead of a single file
          - sourcePath: ./example/copy_folder
            destinationPath: /path/in/container/copy_folder


      # The following properties are explained in the General properties section above
      environment: []
      urlMappings: []
      exports: []
----

==== Docker Compose node

The docker compose node is a very tricky type of node because we use testcontainer library, which is not exactly up to date in terms of docker compose support.
So many of the yaml compose files will need to be modified to work with the testcontainer library.

For now, we support the ePA2 FD module and the DEMIS Meldeportal.

If you want to use your own compose files, please note that Tiger copies and processes your yml files to the target/tiger-testenv-mgr/$+{serverId}+ folder, replacing all variable/property expressions (for details check xref:tigerConfiguration.adoc#_tiger_configuration[this chapter]).

The processing/copying flattens the file hierarchy, thus you must not depend on any additional file resources in your docker compose files.
Each copied compose file will have a random UUID appended to its filename.

NOTE: To use this server type you must include the tiger-cloud-extension dependency!

[source,yaml,title="Docker compose configuration"]
----
servers:
  type: compose
  dependsUpon: csv string
  startupTimeoutSec: int
  # OPTIONAL the logs of the docker compose are also written to a file, if no logFile is
  # specified a default name will be used
  logFile: ./target/serverLogs/dockerCompose.log

  # MANDATORY list of yaml files to use to start up the services.
  # The entries can either be file paths or if starts with
  # classpath:....  a reference to a yaml file contained in the class path
  # (it could also be located inside a jar that is in the class path)
  source:
    - classpath:/de/gematik/test/tiger/testenvmgr/epa/titus-epa2.yml
    - classpath:/de/gematik/test/tiger/testenvmgr/epa/titus-epa2-local.yml
----

[source,yaml,title="Demis docker compose example"]
----
servers:
  demis_001:
    type: compose
    source:
      - classpath:/de/gematik/test/tiger/testenvmgr/demis/demis_localhost.yml
    startupTimeoutSec: 180
----

==== External Jar node

The External Jar node is along with the Docker container node the most important/used node for test environments.
Any Jar archive executable which can be started with the `java -jar` command can be configured as an external Jar node.

The options list are arguments added immediately after the java executable, while the arguments list is appended after the -jar argument.

The working directory is the place where the jar is executed from.
So if your jar archive expects some configuration files make sure to choose the folder appropriately.

If `workingDir` is not set, Tiger defaults to the parent directory of the jar file for `local:` sources, or the OS temp folder for downloaded jars.

Relative paths for both `source` and `workingDir` are resolved relative to the location of the main `tiger.yaml` file.

If using the `local:` prefix you can also use wildcards to find any matching jar-files.
Tiger will use the following order to try to find a matching file:

- The path given in `source` directly (absolute, or resolved from the tiger.yaml location if relative)
- In the working directory, a file whose name matches the filename part of the source (fallback for bare filenames)
- In the working directory, a file whose name matches a wildcard pattern in the source (eg. `app-*.jar`)

[source,shell script]
----
java ${options} -jar externalJar.jar ${arguments}
----

[source,yaml,title="External jar configuration"]
----
servers:
    externalJar_001:
      hostname: mySpecialJar
      type: externalJar
      dependsUpon: csv string
      startupTimeoutSec: int

      # MANDATORY SINGLE ENTRY URL from where to download the Jar archive.
      # If the entry starts with "local:" followed by a file path the jar archive
      # is expected to be available at that location and no download is performed.
      # Only one entry is expected for this node type. Additional entries are silently ignored.
      source:
        - http://myjars.download.org/myproject/myjar.jar
      # MANDATORY URL to check for the successful startup of this node.
      # A successful start is indicated by ANY answer on this URL.
      # Any status is accepted as long as there is an answer.
      # If set to "NONE" no check is performed and
      # the test environment manager will wait for the startup timeout.
      healthcheckUrl: http://127.0.0.1:8080
      # OPTIONAL only declare the server healthy once the specified return code
      # is given
      healthcheckReturnCode: int
      # OPTIONAL the logs of the externalJar are also written to a file, if no logFile is
      # specified a default name will be used
      logFile: ./target/serverLogs/externalJar_001.log

      externalJarOptions:
        # OPTIONAL folder from where to start the external jar.
        # If not set, Tiger defaults to the parent directory of the jar file (for local: sources)
        # or the OS temp folder (for downloaded jars).
        # Relative paths are resolved relative to the location of the tiger.yaml file.
        # A non-existent directory is created automatically.
        workingDir: /home/user/test/myspecificjar
        # OPTIONAL Options to pass in to the java executable call.
        options: []
        # OPTIONAL provide additional arguments to the jar archive call.
        # Default value is empty.
        arguments:
          - --testarg1
          - -singledasharg2
          - --paramarg3=testvalue1

      # The following properties are explained in the General properties section above
      environment: []
      urlMappings: []
      exports: []
----

By default, the JVM used to start the JAR-File is the taken from the `java.home` system property, thus using the same JVM with which Tiger was started.
To change the JVM used you can set the property `tiger.lib.javaHome` (e.g. by setting `-Dtiger.lib.javaHome`, by setting `TIGER_LIB_JAVAHOME` in the environment or by setting `lib.javaHome` in the `tiger.yaml`).

==== External URL node

The symbolic node type that will not start a server instance, but simply allows external services to be used via the configured hostname.
This is achieved by the test environment manager instructing the local Tiger Proxy to provide a route for the symbolic hostname to the external URL of the service.

So, in the following example, the test suite can send HTTP(S) requests to the server "http://myExternalServer" via the local Tiger Proxy, which will be rerouted to the external URL "https://www.medizin.de".
If it is ever necessary to change the external URL, the test suite does not have to be modified, only the routing configuration for the node has to be changed.

Given the nature of this type, the environment section has no effect and is not to be used.

[source,yaml,title="External URL configuration"]
----
servers:
  externalUrl_001:
      hostname: myExternalServer
      type: externalUrl
      dependsUpon: csv string
      startupTimeoutSec: int

      # MANDATORY URL of the external server
      source:
        - https://www.medizin.de

      # OPTIONAL URL to check for successful startup of this node.
      # A successful start is indicated by ANY answer on this URL.
      # Any status is accepted as long as there is an answer.
      # If the value is not set, then no health check is carried out
      # in the startup phase, instead the startupTimeout is waited for.
      # After this timeout it is assumed that the server is up.
      healthcheckUrl: https://www.medizin.de/healthyState.jsp
      # OPTIONAL only declare the server healthy once the specified return code
      # is given
      healthcheckReturnCode: int
      # OPTIONAL the logs of the externalUrl are also written to a file, if no logFile is
      # specified a default name will be used
      logFile: ./target/serverLogs/externalUrl_001.log

      # The following properties are explained in the General properties section above
      # IGNORE for this type as it has no effect
      environment: []
      urlMappings: []
      exports: []
----

==== Helm Chart node

The helm chart node allows to start a helm chart from the configured source (local helm chart file / folder or remote helm chart).
The helm chart is started and the server is ready when all pods are up and running, if port-forward is used (if exposedPorts are set), then port-forwarding is also done and the startup is finished and the service can be used for testing.

NOTE: To use this server type you must include the tiger-cloud-extension dependency!

[source,yaml,title="Helm chart configuration"]
----

servers:
  testHelmChart_Nginx:
    type: helmChart
    startupTimeoutSec: 50
    # MANDATORY repository from where to download the docker image
    # if the helm chart is stored on the local file system that the
    # workingDir should be set.
    source:
      - bitnami/nginx
    # OPTIONAL version of the image
    version: 1.1.0
    helmChartOptions:
      # The kubernetes context
      context:
      # OPTIONAL if no working directory is set the default . is used.
      # if the helm chart is stored on the local file system the workingDir
      # should be set.
      workingdir:
      # OPTIONAL prints out debug messages if set to true, default is false.
      debug: true
      # OPTIONAL override the POD_NAMESPACE environment variable if set.
      # if not set, "default" will be used.
      nameSpace: buildslaves
      # MANDATORY pod name of the helm chart
      podName: test-tiger-nginx
      # OPTIONAL key-value pairs that will be used for starting the helm chart
      values:
      # OPTIONAL should contain a list of pods for the health check, regex can be used.
      healthcheckPods:
        - test-tiger-nginx-.*
      # OPTIONAL contains a list of regex to identify the pods whose logs
      # should be forwarded to the console and Tiger Workflow UI.
      logPods:
        - test-tiger-nginx.*
      # OPTIONAL contains a list that will be used for the port forwarding,
      # if empty no port forwarding is done. The syntax is:
      # <POD_NAME_OR_REGEX>,<LOCAL_PORT>:<FORWARDING_PORT>[,<LOCAL_PORT>:<FORWARDING_PORT>]*
      exposedPorts:
        - test-tiger-nginx.*,8080:80
----

==== Tiger Proxy node

The most complex and versatile node type.
The Tiger Proxy will be started as an embedded spring boot application.
This way the start-up time can be minimized, and it is always guaranteed to start the current version.

[source,yaml,title="Tiger Proxy configuration"]
----
servers:
    tigerProxy_001:
      hostname: myTigerProxy
      type: tigerProxy
      dependsUpon: csv string
      startupTimeoutSec: int

      tigerProxyConfiguration:
        # OPTIONAL port of the web user interface and the proxy management
        # (e.g. rbel-message forwarding)
        # Default value is empty, which means a random port will be used.
        # The chosen port is stored with the key tiger.internal.localproxy.admin.port in
        # the TigerGlobalConfiguration
        adminPort: 8080
        # OPTIONAL server name of the node this proxy shall be used as reverse proxy for.
        # If set the routes will be configured appropriately.
        # Default value is empty.
        proxiedServer: externalJar_001
        # OPTIONAL port of the proxy, where the proxy expects to receive proxy requests
        # Default value is empty, which means a random port will be used.
        proxyPort: 3128
        # OPTIONAL protocol the proxy is expecting requests in. One of [http|https]
        # Default value is http
        proxiedServerProtocol: http
        # configures the proxy itself. For more details
        # please check the chapter about the local test suite Tiger Proxy below
        ...
        proxyRoutes:
          - from: http://foobar
            # defines a forward-proxy-route from this server...
            to: https://cryptic.backend/server/with/path
            # to this server
        ...

      # The following properties are explained in the General properties section above
      environment: []
      urlMappings: []
      exports: []
----

The configuration of the Tiger Proxy is explained in detail in the section xref:_configuring_the_local_test_suite_tiger_proxy[]

==== httpbin node

The httpbin simply starts a https://github.com/gaul/java-httpbin[httpbin] server.
This provides several endpoints against which you can perform all kinds of http requests.
The server port on which the server starts can be configured.

[source,yaml,title=httpbin configuration]
httpbin:
    type: httpbin
    serverPort: ${free.port.0}
    healthcheckUrl: http://localhost:${free.port.0}/status/200

=== Provided node templates

Besides these basic nodes we also support tailored templates for nodes like IDP, ePA, ERp and DEMIS.
This should allow you to bring up project specific test environments very fast.

All currently supported templates can be found in the tiger-testenv-mgr modul in the yaml file at /src/main/resources/de/gematik/test/tiger/testenvmgr/templates.yaml

To use such a template, just use the template attribute:

[source,yaml]
----
myPersonalTestIDPInTheRU:
  template: idp-rise-ru
----

or if you want to have an environment with a local reference implementation of the ERezept Fachdienst

[source,yaml]
----
myLocalTestIDP:
  template: idp-ref
  hostname: idp

myLocalTestERp:
  template: erzpt-fd-ref
  dependsUpon: myLocalTestIDP
----

==== Local IDP reference nodes

This template provides the reference implementation of the IDP server as a local docker container.
The docker image is loaded from a gematik internal docker registry server.

The system property IDP_SERVER is set to the URL of the Discovery Document end point and is available for all subsequently initiated test environment nodes.

==== External IDP RISE instance nodes

The idp-rise-ru template provides the RU instance of RISE's IDP server as an "external URL".
The system properties IDP_SERVER and GEMATIK_TESTCONFIG are set to the URL of the Discovery Document end point and a config-file for the IDP test suite respectively.
They are available for all subsequently initiated test environment nodes.

The idp-rise-tu template provides the TU instance accordingly.

==== Local ERp reference nodes

This template provides the reference implementation of the eRezept server as a local docker container.
The docker image is loaded from a gematik internal docker registry server.
Make sure that an IDP server node is instantiated before the ERp FD is started and that it is available under http://idp or adapt the environment variable configuration.

A large list of environment variables is set.
But don't worry, it is just the server that uses them.

==== Local ePA2 reference nodes

This template provides the gematik reference Aktensystem simulation as docker compose.

==== Local PSSim node

This template provides a Primärsystem simulation (as a jar), usable for ePA.
See https://wiki.gematik.de/display/PTP/epa-ps for more information.

==== Local KonSim node

This template provides a Konnektor simulation (as external jar).
See https://wiki.gematik.de/display/PTP/KonSim for more information.

==== Local ePA FdV Sim

This template provides FdV simulation, usable for ePA.

==== Local DEMIS reference nodes

This template provides the DEMIS Meldeportal as local docker compose.

[#_configuring_the_local_test_suite_tiger_proxy]
=== Configuring the local test suite Tiger Proxy

The local Tiger Proxy for the test suite can be configured by using the following section(s) in the `tiger.yaml` file.
For more information about what the Tiger Proxy is and how it works see the chapter xref:tigerProxy.adoc#_tiger_proxy_basics[Tiger Proxy basics]

[source,yaml]
----
# Flag whether to activate the local Tiger Proxy. The local tiger proxy field will be null if this property is set to false
# Default value is true
localProxyActive: true

# Specifiy additional yaml-files to read in during startup
additionalConfigurationFiles:
  -
    # the path to the file to read
    filename: specialEnvironment.yaml
    # the key to which to map the given file. "tiger" is the base-key for the tiger.yaml-file
    baseKey: tiger

# the block where all the Tiger Proxy configuration properties are located
tigerProxy:
  # the port which will be used for administration (webUI, mesh-Setup,...)
  adminPort: 7777
  # port which will be used to proxy requests
  proxyPort: 6666
  additionalProxyPorts:
    - 5555 # additional port which will be used for proxying
  # logLevel of the proxy-server. DEBUG and TRACE will print traffic, so use with care!
  proxyLogLevel: TRACE
  # section to configure whether and where the proxy should dump a tiger traffic file on shutdown
  fileSaveInfo:
    # should the traffic be logged to a file?
    writeToFile: true
    # configure the file name
    filename: "foobar.tgr"
    # default false, removes any potentially existing saved tgr traffic file on startup.
    clearFileOnBoot: true
    # read traffic from a file at startup
    sourceFile: "sourceFile.tgr"
    # filter messages read from file (JEXL expression).
    # Only message for which this expression is true will be loaded.
    readFilter: "message.statusCode == '200'"

  # a list of routing entries the proxy should apply to traffic
  proxyRoutes:
      # defines a forward-proxy-route from this server...
    - from: http://foobar
      # to this server
      to: https://cryptic.backend/server/with/path
      # reverse proxy-route. http://<tiger-proxy>/blub will be forwarded
    - from: "/blub"
      to: "https://another.de/server"
      # the traffic for this route will NOT be logged (default is false)
      disableRbelLogging: true
      hosts:
        - "www.google.com"
        - "www.bing.com"
      # For reverse proxy-routes this allows to differentiate requests based on the host-header. This is useful when the DNS-resolvement of the client can be influenced, but not the ports used.

  # a list of modifications that will be applied to every proxied request and response
  modifications:
    # a condition that needs to be fulfilled for the modification to be applied
    # (uses JEXL grammar)
  - condition: "isRequest"
    # which element should be targeted?
    targetElement: "$.header.user-agent"
    # the replacement string to be filled in.
    # This modification will replace the entire "user-agent" in all requests
    replaceWith: "modified user-agent"

  - condition: "isResponse && $.responseCode == 200"
    targetElement: "$.body"
    # The name of this modification.
    # This can be used to identify, alter or remove this modification.
    # The name is optional, but if it is used, it has to be unique.
    name: "body replacement modification"
    # This will replace the body of every 200 response completely with the given json-string
    # (This ignores the existing body. For example this could be an XML-body.
    # Content-Type-headers will NOT be set accordingly).
    replaceWith: "{\"another\":{\"node\":{\"path\":\"correctValue\"}}}"
  - targetElement: "$.body"
    # The given regex will be used to target only parts of targeted element.
    regexFilter: "ErrorSeverityType:((Error)|(Warning))"
    # This modification has no condition,
    # so it will be applied to every request and every response
    replaceWith: "ErrorSeverityType:Error"

  # can be used if the target-server (to) is behind another proxy
  forwardToProxy:
    hostname: 192.168.110.10
    port: 3128
    type: HTTP
    noProxyHosts:
      - "localhost"
  # The Tiger Proxy will route google.com to google.com even if no route is set.
  # The traffic routed via this "forwardAll"-routing will be logged by default
  # (meaning it will show up in the Rbel-Logs and be forwarded to tracing-clients)
  # This can be deactivated by setting this flag to false
  activateForwardAllLogging: true
  # Limits the rbel-Buffer to approximately this size.
  # Note: When Rbel debugging is activated the size WILL vastly exceed this limit!
  rbelBufferSizeInMb: 1024
  # If set to false disables traffic-analysis by Rbel.
  # Deactivating will not impede proxy-forwarding nor
  # the traffic-endpoints.
  activateRbelParsing: true
  # While parsing the Tiger Proxy can block the communication from completing.
  # The end answer from the Tiger Proxy is only transmitted when parsing is completed
  # (and the message pair can be seen in the log). When 'false' the parsing is done
  # asynchronous.
  # Default is true ONLY for the local Tiger Proxy, otherwise default is false!!
  parsingShouldBlockCommunication: false
  # This will share the WebUI-Resources (various CSS-files) from the Tiger Proxy
  # locally, thus enabling usage when no internet connection exists
  localResources: true
  # When active the host-headers are rewritten even for a reverse-proxy-route
  rewriteHostHeader: true
  # This option can be used to deactivate TLS-Termination. Only deactivate this in
  # conjunction with a directReverseProxy
  activateTlsTermination: true

  tls:
    # Can be used to define a CA-Identity to be used with TLS. The Tiger Proxy will
    # generate an identity when queried by a client that matches the configured route.
    # If the client then in turn trusts the CA this solution will provide you with a seamless
    # TLS experience. It however requires access to the private-key of a trusted CA.
    serverRootCa: "certificate.pem;privateKey.pem;PKCS8"
    # Alternative solution: now all incoming TLS-traffic will be handled using this identity.
    # This might be easier but requires a certificate
    # which is valid for the configured routes
    serverIdentity: "certificateAndKeyAndChain.p12;Password"
    # Defines which SSL-Suites are allowed. This will delete all default-suites and only add the one
    # defined here. This configures the server-side of the proxy. Available values can be found here:
    # https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html
    serverSslSuites:
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    # This configures the SSL-Suites for the client-side. Available values can be found here:
    # https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html
    clientSslSuites:
      - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    # Define which TLS protocols the server will allow/use. Available values can be found here:
    # https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html
    clientSupportedGroups:
      - "brainpoolP256r1"
      - "brainpoolP384r1"
      - "prime256v1"
      - "secp384r1"
    # Define the groups to be offered in the "client hello" message. More information can be found here:
    # https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.7
    serverTlsProtocols:
      - "TLSv1.2"

    # This identity will be used as a client-identity for mutual-TLS when forwarding to
    # other servers. The information string can be
    # "my/file/name.p12;p12password" or
    # "p12password;my/file/name.p12" or
    # "cert.pem;key.pkcs8" or
    # "rsaCert.pem;rsaKey.pkcs1" or
    # "key/store.jks;key" or
    # "key/store.jks;key1;key2" or
    # "key/store.jks;jks;key"
    #
    # Each part can be one of:
    # * filename
    # * password
    # * store-type (accepted are P12, PKCS12, JKS, BKS, PKCS1 and PKCS8)
    forwardMutualTlsIdentity: "directory/where/another/identityResides.jks;changeit;JKS"
    # domain which will be used as the server address in the TLS-certificate
    domainName: deep.url.of.server.de
    # Alternate names to be added to the TLS-certificate
    # (localhost and 127.0.0.1 are added by default)
    alternativeNames:
      - localhost
      - 63.54.54.43
      - foo.bar.server.com
    # the file into which the master-secrets are written. For this to work
    # the tiger-java-agent has to be attached to the JVM
    # (eg. -javaagent:tiger-java-agent-3.1.4.jar). This can be done by
    # executing the goal 'attach-tiger-agent' to the tiger-maven-plugin.
    masterSecretsFile: "masterSecretsFile.txt"

  # the given folders are loaded into RBel for analysis. This is only necessary to decrypt
  # traffic when analyzing it. It has no effect on the proxy-functions themselves.
  keyFolders:
  - .

  # Filter out any messages larger from parsing (saving performance)
  skipParsingWhenMessageLargerThanKb: 8000
  # Filter out any messages (or message parts) from displaying
  skipDisplayWhenMessageLargerThanKb: 512

  # A list of upstream Tiger Proxies. This proxy will try to connect to all given sources to
  # gather traffic via the STOMP-protocol. If any of the given endpoints are not accessible
  # the server will not boot. (fail fast, fail early)
  trafficEndpoints:
    - http://another.tiger.proxy:<proxyPort>
  trafficEndpointConfiguration:
    # the name for the traffic Endpoint. can be any string, which will be
    # displayed at /tracingpoints
    name: "tigerProxy Tracing Point"
----

=== Standalone mode vs. implicit startup with test suite

If your test environment is very "expensive" to start or if you are developing your test suite scenarios, thus starting many test runs in a short time, you might want to keep your test environment running and not shut it down after each run.
To do so, you can simply use the tiger maven plugin to start your test environment in standalone mode.

First prepare a standalone test environment configuration file (call it for example tiger-standalone.yaml) containing all the server nodes needed and with a deactivated the local tiger proxy section.

Now set the env var TIGER_TESTENV_CFGFILE or the Java system property tiger.testenv.cfgfile to point to this file.

If you start the test environment manager standalone, it will keep the nodes running until you enter quit into the console or kill the process with Ctrl + C or the operating equivalent commando to the UNIX command kill ${PROCESS_ID}.
In the latter case it is not guaranteed that all processes are cleanly shut down.
Please check your process list with operating system-specific tools.

[source,shell script]
----
export TIGER_TESTENV_CFGFILE=....../tiger-standalone.yaml
mvn tiger:setup-testenv
----

In case you also need cloud extension server types (docker, helmchart) make sure to add the Tiger cloud extensions as dependency to the **plugin block**.

Now before starting your test suite scenarios you need to

* disable / remove the test nodes in your default `tiger.yaml` (either by setting the property active to false or remove the server node entry completely).
If you forget to do this, two nodes will be instantiated (one from the standalone test environment manager and the second during test run from the test environment manager started via the test suite hooks).
* and add routes for each node to the local tiger proxy.
If you forget to do this, your test suite will not be able to access the test nodes under their configured hostname as this configuration is only known to the standalone test environment manager and NOT to the local tiger proxy started by the test suite hooks.

The best practice is to have three test environment configuration files:

* tiger-standalone.yaml to enable a persistent test environment during the development of test suite scenarios
* tiger-nonodes.yaml for the test suite that will instantiate no nodes but only configure the routes to the nodes from the standalone test environment manager
* `tiger.yaml` a complete configuration that can be used in CI or after the test suite development is completed.

The first and the latter most of the time are identical besides the root level flag localProxyActive.
So you may skip the first and just use it with two different values being set.

=== Using Environment variables and system properties

In many configuration values (e.g. `exports`, `environment`, `source`, etc.), placeholders like `${PORT:xxxx}` or `${NAME}` can be used.
These are replaced at runtime with the actual values (e.g. the exposed port of a Docker container or the hostname of a node).

