[#_tiger_test_environment_manager]
== Tiger Test Environment Manager

As outlined in xref:tiger_user_manual.adoc#_overview[the overview section], the test environment manager is one of the three core components of the Tiger test framework.
Its main task is to start various test server nodes configured in the `tiger.yaml` configuration file and initialize the local tiger proxy for the test suite.

=== Tiger.yaml files and how they are chosen and loaded

The test environment manager first checks if the environment variable `TIGER_TESTENV_CFGFILE` is set and tries to load the configuration file from this value.
If the environment variable is not set, it searches for files named `tiger.yaml` or `tiger.yml`.
If none of these files exist, it will fail the start-up.

It then loads further YAML files:

* `tiger-$+{hostname}+.yaml` and `tiger-$+{hostname}+.yml` are read and allow computer-dependent configuration.
The hostname is the name of your own computer in the network (on Windows machines, typically the computer name).
* `tiger-$+{profile}+.yaml` is read if the system property `profile` or the environment variable `PROFILE` is set.
The file must be located in the same folder as the `tiger.yaml` file.
Additionally, you can configure a default profile in the Tiger configuration, which will be loaded when none is set via environment variable or system property.
See xref:tigerTestLibrary.adoc#_tiger_test_lib_configuration[Tiger test lib configuration] for more details.

During the start-up phase it also informs the local tiger proxy about the hostnames each node has configured, so that the local tiger proxy can create appropriate routing entries in its own configuration.

To configure your test environment, you can compose the `tiger.yaml` file manually.
There is a JSON schema available for your IDE to assist with editing the `tiger.yaml`: https://json.schemastore.org/gematik-tiger.json.

The nodes configured in the YAML file are started asynchronously unless the `dependsUpon` property is set.

Before writing your own `tiger.yaml` configuration files, ensure you are familiar with YAML syntax and structure.

[#_yaml_loading_and_overriding]
=== YAML loading and overriding logic

The Tiger test environment loads configuration from several YAML files, depending on environment variables, hostnames, and profiles.
The order and logic are as follows:

- If the environment variable `TIGER_TESTENV_CFGFILE` is set, this file is loaded first.
- If not, `tiger.yaml` or `tiger.yml` in the working directory is loaded.
- Hostname-specific files (`tiger-${hostname}.yaml` or `.yml`) are loaded next.
- Profile-specific files (`tiger-${profile}.yaml`) are loaded if a profile is set via system property or environment variable.
- Additional configuration files can be loaded via the `tiger.additionalConfigurationFiles` list in the main config.

For details, see xref:tigerConfiguration.adoc#_additional_yaml_files[Additional YAML files].

==== Exports

All `exports` entries of a node are available for subsequent nodes and can be used in their configuration (e.g. in Docker `environment`, tiger proxy `proxyRoutes`, etc.).


<<<

include::serverTypes.adoc[]

=== Server type example

Here is a little example of how the server names are set and used and how the server is reachable via the tiger proxy.

[source,yaml,title="Example with three external jar servers"]
----
servers:
# here the server name is "identityServer" and
# the server is reachable under "identityServer" via the tiger proxy
  identityServer:
    type: externalJar
    # important: the source entry must not contain any spaces.
    source:
      - local:../octopus-identity-service/target/octopus-identity-service-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.identity}/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port=${tiger.ports.identity}
        - --services.shopping=http://myShoppingServer

  # here the server name is "shoppingServer"
  # but the server is reachable under "myShoppingServer" via the tiger proxy because hostname is set
  shoppingServer:
    hostname: myShoppingServer
    type: externalJar
    source:
      - local:../octopus-shopping-service/target/octopus-shopping-service-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.shopping}/inventory/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port = ${tiger.ports.shopping}
        - --services.identity=http://identityServer

  testClient:
    type: externalJar
    source:
      - local:../octopus-example-client/target/octopus-example-client-1.0-SNAPSHOT.jar
    healthcheckUrl: http://localhost:${tiger.ports.client}/testdriver/status
    externalJarOptions:
      options:
        - -Dhttp.proxyHost=127.0.0.1
        - -Dhttp.proxyPort=${tiger.tigerProxy.proxyPort}
      arguments:
        - --server.port=${tiger.ports.client}
        # here are the examples how the servers are reachable
        - --services.shopping=http://myShoppingServer
        - --services.identity=http://identityServer
----

The configuration of the tiger proxy is explained in detail in the section xref:tigerProxy.adoc#_tiger_proxy_basics[Tiger Proxy basics]

=== Standalone mode vs. implicit startup with test suite

If your test environment is very "expensive" to start or if you are developing your test suite scenarios, thus starting many test runs in a short time, you might want to keep your test environment running and not shut it down after each run.
To do so, you can simply use the tiger maven plugin to start your test environment in standalone mode.

First prepare a standalone test environment configuration file (call it for example tiger-standalone.yaml) containing all the server nodes needed and with a deactivated the local tiger proxy section.

Now set the env var TIGER_TESTENV_CFGFILE or the Java system property tiger.testenv.cfgfile to point to this file.

If you start the test environment manager standalone, it will keep the nodes running until you enter quit into the console or kill the process with Ctrl + C or the operating equivalent commando to the UNIX command kill ${PROCESS_ID}.
In the latter case it is not guaranteed that all processes are cleanly shut down.
Please check your process list with operating system-specific tools.

[source,shell script]
----
export TIGER_TESTENV_CFGFILE=....../tiger-standalone.yaml
mvn tiger:setup-testenv
----

In case you also need cloud extension server types (docker, helmchart) make sure to add the Tiger cloud extensions as dependency to the **plugin block**.

Now before starting your test suite scenarios you need to

* disable / remove the test nodes in your default `tiger.yaml` (either by setting the property active to false or remove the server node entry completely).
If you forget to do this, two nodes will be instantiated (one from the standalone test environment manager and the second during test run from the test environment manager started via the test suite hooks).
* and add routes for each node to the local tiger proxy.
If you forget to do this, your test suite will not be able to access the test nodes under their configured hostname as this configuration is only known to the standalone test environment manager and NOT to the local tiger proxy started by the test suite hooks.

The best practice is to have three test environment configuration files:

* tiger-standalone.yaml to enable a persistent test environment during the development of test suite scenarios
* tiger-nonodes.yaml for the test suite that will instantiate no nodes but only configure the routes to the nodes from the standalone test environment manager
* `tiger.yaml` a complete configuration that can be used in CI or after the test suite development is completed.

The first and the latter most of the time are identical besides the root level flag localProxyActive.
So you may skip the first and just use it with two different values being set.

=== Using Environment variables and system properties

In many configuration values (e.g. `exports`, `environment`, `source`, etc.), placeholders like `${PORT:xxxx}` or `${NAME}` can be used.
These are replaced at runtime with the actual values (e.g. the exposed port of a Docker container or the hostname of a node).

