= Tiger maven plugin

This plugin allows to dynamically generate the JUnit driver classes that are then used in the Surefire plugin to start the test runs. And replaces the serenity maven plugin to generate Serenity BDD test reports.

== Generate Drivers goal

NOTE: You may decide to manually write your own JUnit driver classes in which case you can omit this plugin.

To activate this feature in your maven project add the following plugin block to your <build><plugins> section:

[source,xml]
----
include::../doc/examples/tigerOnly/pom.xml[tag="generator-plugin"]
----


.Mandatory configuration properties
* **List[glue] glues** (mandatory) +
list of packages to be included as glue or hooks code

.Optional configuration properties or properties with default values
* List[include] includes (mandatory) +
list of include patterns for feature files in Ant format (directory/**.feature)
* String featuresDir (default: local working directory) +
root folder from where to apply includes and excludes
* List[exclude] excludes (default: empty) +
list of exclusion patterns for feature files in Ant format (directory/**.feature)
* boolean skip (default: false) +
flag whether to skip the execution of this plugin
* String driverPackage (default: de.gematik.test.tiger.serenity.drivers) +
package of the to be generated driver class
* String driverClassName (default: Driver${ctr}) +
Name of the to be generated driver class.

NOTE:  The ctr token ${ctr} is mandatory! For more details see section below

* String templateFile (default: null which means that the plugin will use the built-in template file) +
  Optional path to a custom template file to be used for generating the driver Java source code file.
  ** The plugin currently supports the following list of tokens:
    *** ${ctr} +
counter value that is unique and incremented for each feature file.
    *** ${package} +
will be replaced with package declaration code line of the driver class.
Either empty or of the pattern "package xxx.yyy.zzz;" where xxx.yyy.zzz is replaced with the configured driverPackage configuration property.
    *** ${driverClassName} +
name of the driver class (with the ctr token already being replaced with the incrementing counter value).
    *** ${feature} +
path to the feature file(s).
    *** ${glues} +
comma separated list of glue/hook packages as specified by the glues configuration property.

=== Manually creating driver classes

For each feature (or use wildcards / directories for single driver class) you can implement a driver class based on the example code below.

```java
package de.gematik.test.tiger.integration.YOURPROJECT;

import io.cucumber.junit.CucumberOptions;
import io.cucumber.junit.TigerCucumberRunner;
import org.junit.runner.RunWith;

@RunWith(TigerCucumberRunner.class)
@CucumberOptions(
    features = {"src/test/resources/features/YOURFEATURE.feature"},
    plugin = {"json:target/cucumber-parallel/1.json"},
    monochrome = false,
    glue = {"de.gematik.test.tiger.glue",
        "ANY ADDITIONAL PACKAGES containing GLUE or HOOKS code"})
public class Driver1IT {

}
```

== Generate Reports goal

The second execution block in the example XML section above will trigger the report creation. There are no properties for configuration at the moment.
Two reports will be generated under target/site/serenity:

* A simple HTML single page report for emailing (serenity-summary.html)
* A fancy detailed overall report (index.html)

== Start Tiger test environment in stand alone mode

Adding the plugin as shown below will allow you to start a test enviroment in standalone mode by starting mvn as follows: ```mvn tiger:setup-testenv```.
Please be aware that this is a blocking call, you may specify a timeout configuration property ```autoShutdownAfterSeconds``` with timeout in seconds. To prematurely stop the process either press Ctrl+C in your console or kill it with operating system specific kill commands / tools. In order to customize the tiger yaml to be used either set the environment variable ```TIGER_TESTENV_CFGFILE``` or set the system property ```tiger.testenv.cfgfile```.

```xml
           <plugin>
                <groupId>de.gematik.test</groupId>
                <artifactId>tiger-maven-plugin</artifactId>
                <version>${version.tiger}</version>
            </plugin>
```
